### ISSUE TITLE
Planet

### ISSUE THREAD

**Issue by OreQr** [SebLague/Marching-Cubes#14]
how to get the same effect as in 4:28 because you came out the planet in the movie and I have a circle

**Comment by andrewdavidjamesburke** [comment]
The mesh generator has a slot to change the type of density. 
1. Create an empty  game object under density generators.
2. Apply the sphere density script.
3. Insert the sphere density compute into the script in the inspector
4. Switch the density on the Mesh Gen to your new Game object with the density attached.
5. Adjust the radius so you can see it.
6. Play with settings.

I recommend creating a sphere mesh generator object and disabling the main mesh gen object so you dont lose your settings.

**Comment by OreQr** [comment]
![image](https://user-images.githubusercontent.com/50458706/91351118-0923ee00-e7e8-11ea-83ea-6ed2fd7b829e.png)

And how to make bumps on this ball because I changed and there is no

**Comment by isuckatgamedev** [comment]
Okay so I know I am 3 years late but i found a fix: You have to modify the normal shader to include the planet formula like this: Noisedensity.compute: #pragma kernel Density
#include "/Includes/Density.compute"
#include "/Includes/Noise.compute"

// Noise settings
StructuredBuffer<float3> offsets;
int octaves;
float lacunarity;
float persistence;
float noiseScale;
float noiseWeight;
float floorOffset;
float weightMultiplier;
bool closeEdges;
float hardFloor;
float hardFloorWeight;
float radius;

float4 params;

[numthreads(numThreads, numThreads, numThreads)]
void Density (int3 id : SV_DispatchThreadID)
{
    if (id.x >= numPointsPerAxis || id.y >= numPointsPerAxis || id.z >= numPointsPerAxis) {
        return;
    }

    float3 pos = centre + id * spacing - boundsSize / 2.0;
    float offsetNoise = 0.0;

    float noise = 0.0;

    float frequency = noiseScale / 100.0;
    float amplitude = 1.0;
    float weight = 1.0;
    for (int j = 0; j < octaves; j++) {
        float n = snoise((pos + offsetNoise) * frequency + offsets[j] + offset);
        float v = 1.0 - abs(n);
        v = v * v;
        v *= weight;
        weight = max(min(v * weightMultiplier, 1.0), 0.0);
        noise += v * amplitude;
        amplitude *= persistence;
        frequency *= lacunarity;
    }
    
    //float finalVal = -(pos.y + floorOffset) + noise * noiseWeight + (pos.y % params.x) * params.y;
    float finalVal = radius - length(pos) + noise * noiseWeight + (pos.y % params.x) * params.y;

    if (pos.y < hardFloor) {
        finalVal += hardFloorWeight;
    }

    if (closeEdges) {
        float3 edgeOffset = abs(pos * 2.0) - worldSize + spacing / 2.0;
        float edgeWeight = saturate(sign(max(max(edgeOffset.x, edgeOffset.y), edgeOffset.z)));
        finalVal = finalVal * (1.0 - edgeWeight) - 100.0 * edgeWeight;
    }

    int index = indexFromCoord(id.x, id.y, id.z);
    points[index] = float4(pos, finalVal);
}
Noisedensity.cs:

public class NoiseDensity : DensityGenerator {

    [Header ("Noise")]
    public int seed;
    public int numOctaves = 4;
    public float lacunarity = 2;
    public float persistence = .5f;
    public float noiseScale = 1;
    public float noiseWeight = 1;
    public bool closeEdges;
    public float floorOffset = 1;
    public float weightMultiplier = 1;

    public float hardFloorHeight;
    public float hardFloorWeight;

    public Vector4 shaderParams;

    public float radius;

    public override ComputeBuffer Generate (ComputeBuffer pointsBuffer, int numPointsPerAxis, float boundsSize, Vector3 worldBounds, Vector3 centre, Vector3 offset, float spacing) {
        buffersToRelease = new List<ComputeBuffer> ();

        // Noise parameters
        var prng = new System.Random (seed);
        var offsets = new Vector3[numOctaves];
        float offsetRange = 1000;
        for (int i = 0; i < numOctaves; i++) {
            offsets[i] = new Vector3 ((float) prng.NextDouble () * 2 - 1, (float) prng.NextDouble () * 2 - 1, (float) prng.NextDouble () * 2 - 1) * offsetRange;
        }

        var offsetsBuffer = new ComputeBuffer (offsets.Length, sizeof (float) * 3);
        offsetsBuffer.SetData (offsets);
        buffersToRelease.Add (offsetsBuffer);

        densityShader.SetVector ("centre", new Vector4 (centre.x, centre.y, centre.z));
        densityShader.SetInt ("octaves", Mathf.Max (1, numOctaves));
        densityShader.SetFloat ("lacunarity", lacunarity);
        densityShader.SetFloat ("persistence", persistence);
        densityShader.SetFloat ("noiseScale", noiseScale);
        densityShader.SetFloat ("noiseWeight", noiseWeight);
        densityShader.SetBool ("closeEdges", closeEdges);
        densityShader.SetBuffer (0, "offsets", offsetsBuffer);
        densityShader.SetFloat ("floorOffset", floorOffset);
        densityShader.SetFloat ("weightMultiplier", weightMultiplier);
        densityShader.SetFloat ("hardFloor", hardFloorHeight);
        densityShader.SetFloat ("hardFloorWeight", hardFloorWeight);
        densityShader.SetFloat ("radius", radius);

        densityShader.SetVector ("params", shaderParams);

        return base.Generate (pointsBuffer, numPointsPerAxis, boundsSize, worldBounds, centre, offset, spacing);
    }
}

**Comment by OreQr** [comment]
> Okay so I know I am 3 years late but i found a fix: You have to modify the normal shader to include the planet formula like this: Noisedensity.compute: #pragma kernel Density #include "/Includes/Density.compute" #include "/Includes/Noise.compute"
> 
> // Noise settings StructuredBuffer offsets; int octaves; float lacunarity; float persistence; float noiseScale; float noiseWeight; float floorOffset; float weightMultiplier; bool closeEdges; float hardFloor; float hardFloorWeight; float radius;
> 
> float4 params;
> 
> [numthreads(numThreads, numThreads, numThreads)] void Density (int3 id : SV_DispatchThreadID) { if (id.x >= numPointsPerAxis || id.y >= numPointsPerAxis || id.z >= numPointsPerAxis) { return; }
> 
> ```
> float3 pos = centre + id * spacing - boundsSize / 2.0;
> float offsetNoise = 0.0;
> 
> float noise = 0.0;
> 
> float frequency = noiseScale / 100.0;
> float amplitude = 1.0;
> float weight = 1.0;
> for (int j = 0; j < octaves; j++) {
>     float n = snoise((pos + offsetNoise) * frequency + offsets[j] + offset);
>     float v = 1.0 - abs(n);
>     v = v * v;
>     v *= weight;
>     weight = max(min(v * weightMultiplier, 1.0), 0.0);
>     noise += v * amplitude;
>     amplitude *= persistence;
>     frequency *= lacunarity;
> }
> 
> //float finalVal = -(pos.y + floorOffset) + noise * noiseWeight + (pos.y % params.x) * params.y;
> float finalVal = radius - length(pos) + noise * noiseWeight + (pos.y % params.x) * params.y;
> 
> if (pos.y < hardFloor) {
>     finalVal += hardFloorWeight;
> }
> 
> if (closeEdges) {
>     float3 edgeOffset = abs(pos * 2.0) - worldSize + spacing / 2.0;
>     float edgeWeight = saturate(sign(max(max(edgeOffset.x, edgeOffset.y), edgeOffset.z)));
>     finalVal = finalVal * (1.0 - edgeWeight) - 100.0 * edgeWeight;
> }
> 
> int index = indexFromCoord(id.x, id.y, id.z);
> points[index] = float4(pos, finalVal);
> ```
> 
> } Noisedensity.cs:
> 
> public class NoiseDensity : DensityGenerator {
> 
> ```
> [Header ("Noise")]
> public int seed;
> public int numOctaves = 4;
> public float lacunarity = 2;
> public float persistence = .5f;
> public float noiseScale = 1;
> public float noiseWeight = 1;
> public bool closeEdges;
> public float floorOffset = 1;
> public float weightMultiplier = 1;
> 
> public float hardFloorHeight;
> public float hardFloorWeight;
> 
> public Vector4 shaderParams;
> 
> public float radius;
> 
> public override ComputeBuffer Generate (ComputeBuffer pointsBuffer, int numPointsPerAxis, float boundsSize, Vector3 worldBounds, Vector3 centre, Vector3 offset, float spacing) {
>     buffersToRelease = new List<ComputeBuffer> ();
> 
>     // Noise parameters
>     var prng = new System.Random (seed);
>     var offsets = new Vector3[numOctaves];
>     float offsetRange = 1000;
>     for (int i = 0; i < numOctaves; i++) {
>         offsets[i] = new Vector3 ((float) prng.NextDouble () * 2 - 1, (float) prng.NextDouble () * 2 - 1, (float) prng.NextDouble () * 2 - 1) * offsetRange;
>     }
> 
>     var offsetsBuffer = new ComputeBuffer (offsets.Length, sizeof (float) * 3);
>     offsetsBuffer.SetData (offsets);
>     buffersToRelease.Add (offsetsBuffer);
> 
>     densityShader.SetVector ("centre", new Vector4 (centre.x, centre.y, centre.z));
>     densityShader.SetInt ("octaves", Mathf.Max (1, numOctaves));
>     densityShader.SetFloat ("lacunarity", lacunarity);
>     densityShader.SetFloat ("persistence", persistence);
>     densityShader.SetFloat ("noiseScale", noiseScale);
>     densityShader.SetFloat ("noiseWeight", noiseWeight);
>     densityShader.SetBool ("closeEdges", closeEdges);
>     densityShader.SetBuffer (0, "offsets", offsetsBuffer);
>     densityShader.SetFloat ("floorOffset", floorOffset);
>     densityShader.SetFloat ("weightMultiplier", weightMultiplier);
>     densityShader.SetFloat ("hardFloor", hardFloorHeight);
>     densityShader.SetFloat ("hardFloorWeight", hardFloorWeight);
>     densityShader.SetFloat ("radius", radius);
> 
>     densityShader.SetVector ("params", shaderParams);
> 
>     return base.Generate (pointsBuffer, numPointsPerAxis, boundsSize, worldBounds, centre, offset, spacing);
> }
> ```
> 
> }

Hi, thanks for your reply. Unfortunately, I stopped developing games and using Unity.
