### ISSUE TITLE
Out Of Memory Exception upon Launching in 2019.1.1

### ISSUE THREAD

**Issue by liamdx** [SebLague/Marching-Cubes#2]
Error is in MeshGenerator at line 201: 
"Triangle[] tris = new Triangle[numTris];" 

whenever any scene is run, get the error OutOfMemoryException - Out of Memory

**Comment by SebLague** [comment]
Hi, should work now. Let me know if not!

**Comment by liamdx** [comment]
Yep! this works now, thanks for such a quick fix :)
